apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gloo-ingress-adapter.serviceAccountName" . }}
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.solo.io
  resources:
  - routetables
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
